eureka:  
  server:
    enable-self-preservation: false   
    eviction-interval-timer-in-ms: 1000000
  instance:
    hostname: localhost   
  client:
    fetch-registry: false
    register-with-eureka: false 


server:
  port: 5001