


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
server:
  port: 8081
  
spring:
  application:
    name: second-service
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka      